### ISSUE TITLE
Space between characters

### ISSUE THREAD

**Issue by mzeidhassan** [ukiuki-satoshi/visedit#7]
Hi @ukiuki-satoshi,

First, thanks for the nice module. 

I was testing it, noticed that it adds a space after every single character. This makes the module less useful in many scenarios. 

Please see screen shot.
![image](https://user-images.githubusercontent.com/7589948/69399498-06dfb100-0cf7-11ea-8271-1697f3f12122.png)

Thanks

**Comment by ukiuki-satoshi** [comment]
Hi @mzeidhassan 
thank you for your testing and proposal.
i'll fix it to enable to truncate the spaces by arguments.

**Comment by ukiuki-satoshi** [comment]
I've released ver 1.0.4 which deals with this issue.
now it can truncate spaces by specifying `truncate` option.
```py
se.generate_text(truncate=True)
```

thank you and best regards,
